CREATE TABLE HOTELEMPLOYEE (EMPID NUMBER(5) PRIMARY KEY, PAYRATE NUMBER(5,2),PHONE VARCHAR2(10),NAME VARCHAR2(50) UNIQUE,SSN NUMBER(9) UNIQUE,DOJ DATE, APTNUMBER NUMBER(5),STREET VARCHAR2(50),CITY VARCHAR2(10), STATE VARCHAR2(10),ZIPCODE VARCHAR2(10),AGE NUMBER(3),TYPE VARCHAR2(10));


create table menu(itemid number(5) primary key, itemname varchar2(20) not null, description varchar2(100), price number(5,2) not null, nutriinfo varchar2(50), empid constraint fk_empids references hotelemployee(empid) on delete cascade);

CREATE TABLE INGREDIENTS(INGREDIENTNAME VARCHAR2(25) PRIMARY KEY,CATEGORY varchar2(25) not null, measuringunit varchar2(10));

CREATE TABLE HOTELTABLE(TABLENO NUMBER(5) PRIMARY KEY, STATUS VARCHAR2(20));

CREATE TABLE CUSTOMER_TABLE(NAME VARCHAR2(25),PHONE VARCHAR2(10) PRIMARY KEY,ZIPCODE VARCHAR2(10), TABLENO NUMBER(5));

CREATE TABLE MENU_ORDER( PHONE CONSTRAINT FK_PHO REFERENCES CUSTOMER_TABLE(PHONE)ON DELETE CASCADE, EMPID CONSTRAINT FK_EITH REFERENCES HOTELEMPLOYEE(EMPID)ON DELETE CASCADE,ITEMID CONSTRAINT FK_IFOUR REFERENCES MENU(ITEMID)ON DELETE CASCADE,TOTALPRICE NUMBER(7,2),RATING NUMBER(5));


CREATE TABLE SITSON_DATE(PHONE CONSTRAINT FK_PHT REFERENCES CUSTOMER_TABLE(PHONE),TABLENO CONSTRAINT FK_TNO REFERENCES HOTELTABLE(TABLENO)ON DELETE CASCADE, SITSON_DATE DATE, PRIMARY KEY (PHONE, TABLENO, SITSON_DATE));

CREATE TABLE SUPPLIER(SUPPLIERID NUMBER(5) PRIMARY KEY,SUPPLIERNAME VARCHAR2(50) UNIQUE, PHONE VARCHAR2(10) UNIQUE,BUILDINGNO VARCHAR2(5),STREET VARCHAR2(50),CITY VARCHAR2(20), ZIPCODE VARCHAR2(10),STATE VARCHAR2(20));

CREATE TABLE SUPPLIES(INGREDIENTNAME CONSTRAINT FK_ITHREE REFERENCES INGREDIENTS(INGREDIENTNAME)ON DELETE CASCADE, SUPPLIERID CONSTRAINT FK_SIDO REFERENCES SUPPLIER(SUPPLIERID), PRIMARY KEY (INGREDIENTNAME,SUPPLIERID));


CREATE TABLE SUPPLY_INFO(SUPPLIERID CONSTRAINT FK_SIDT REFERENCES SUPPLIER(SUPPLIERID)ON DELETE CASCADE,INGREDIENTNAME CONSTRAINT FK_IFIVE REFERENCES INGREDIENTS(INGREDIENTNAME), QUANTITY NUMBER(5,2), SUPPLY_DATE DATE, PRIMARY KEY (SUPPLIERID, INGREDIENTNAME, QUANTITY, SUPPLY_DATE));

CREATE TABLE MENU_INGREDIENTS(ITEMID CONSTRAINT FK_IONE REFERENCES MENU(ITEMID), INGREDIENTNAME CONSTRAINT FK_ITWO REFERENCES INGREDIENTS(INGREDIENTNAME) ON DELETE CASCADE,QUANTITY NUMBER(5,2), PRIMARY KEY(ITEMID, INGREDIENTNAME,QUANTITY));

create table date_order(empid constraint fk_empu references hotelemployee(empid) on delete cascade, itemid constraint fk_itemu references menu(itemid) on delete cascade, phone constraint fk_phoneu references customer_table(phone) on delete cascade, order_date date, order_time timestamp, primary key(empid,itemid,phone,order_date,order_time));


CREATE TABLE SHIFT(EMPID CONSTRAINT FK_EIT REFERENCES HOTELEMPLOYEE(EMPID) ON DELETE CASCADE,SIGNIN TIMESTAMP,SIGNOUT TIMESTAMP(6), PRIMARY KEY(EMPID,SIGNIN,SIGNOUT));










